package org.leon.myrpc.demo;

import org.leon.myrpc.annotation.RPCProvider;

/**
 * @author Leon Song
 * @date 2020-12-06
 */
@RPCProvider(serviceInterface = HelloService.class)
public class HelloServiceImpl implements HelloService {
    @Override
    public String hello(String name) {
        return "Hello " + name + ", this is generated by rpc.";
    }
}
